Graphql chal
ChasingFlags/The-Archive pull request #5
Opened 2024-02-08 14:52 UTC by angwenyi4169

Added the Graphql challenges, writeup in progress

2024-02-08 14:55 UTC, angwenyi4169 commented
Added the Graphql challenges, writeup in progress

2024-02-08 14:57 UTC, mogoria approved these changes

2024-02-08 21:11 UTC, evalevanto approved these changes

2024-02-08 21:14 UTC, evalevanto requested changes
Please add a .gitignore and then remove these `__pycache__` folders. Also, please add some details in the README.md as discussed offline.
Otherwise, looks good to me.

2025-08-07 19:39 UTC, evalevanto approved these changes

2025-08-07 19:39 UTC, merged